platform :ios, '8.0'
target :BBShangJia do 
pod 'SVProgressHUD', '~> 2.0.3'
pod 'ReactiveCocoa', '~> 2.5'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDAutoLayout', '~> 2.1.1'
pod 'MJRefresh', '~> 3.1.7'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'UMengAnalytics', '~> 4.0.4'#友盟统计
end

